version: '3.6'

services:
  mysql-develop:
    platform: linux/amd64
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'MBTI_develop'
      MYSQL_ROOT_PASSWORD: '0000'
      TZ: 'Asia/Seoul'
    cap_add:
      - SYS_NICE
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
